<?php

require_once dirname(__FILE__).'/../../../www/plugins/kbi/Integrators/Jucene.php';

/**
 * Test class for Jucene.
 * Generated by PHPUnit on 2011-02-14 at 09:36:53.
 */
class JuceneTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Jucene
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Jucene(array(
			'method' => 'GET',
		));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testGetMethod().
     */
    public function testGetMethod()
    {
        $this->assertEquals('GET', $this->object->getMethod());
    }

    /**
     * @todo Implement testQueryPost().
     */
    public function testQueryPost()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetDocuments().
     */
    public function testGetDocuments()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAddDocument().
     */
    public function testAddDocument()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetDocument().
     */
    public function testGetDocument()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testDeleteDocument().
     */
    public function testDeleteDocument()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
