<?php

require_once dirname(__FILE__).'/../../../www/plugins/kbi/Integrators/Semsol.php';

/**
 * Test class for Semsol.
 * Generated by PHPUnit on 2011-02-14 at 09:38:35.
 */
class SemsolTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Semsol
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Semsol(array(
			
		));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testQueryGet().
     */
    public function testQueryGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
