<?php

require_once '/Volumes/Data/svn/sewebar/trunk/joomla/www/plugins/kbi/XQuery.php';

/**
 * Test class for XQuery.
 * Generated by PHPUnit on 2011-02-14 at 09:38:44.
 */
class XQueryTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var XQuery
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new XQuery(array(
			'action' => 'akce',
			'variable' => 'promenna',
		));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testGetAction()
    {
        $this->assertEquals('akce', $this->object->getAction());
    }

	public function testSetAction()
    {
        $this->object->setAction('test akce');
		$this->assertEquals('test akce', $this->object->getAction());
    }

    public function testGetVariable()
    {
        $this->assertEquals('promenna', $this->object->getVariable());
    }

    public function testSetVariable()
    {
		$this->object->setVariable('test promenna');
		$this->assertEquals('test promenna', $this->object->getVariable());
    }

    /**
     * @todo Implement testQueryPost().
     */
    public function testQueryPost()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetDocuments().
     */
    public function testGetDocuments()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAddDocument().
     */
    public function testAddDocument()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetDocument().
     */
    public function testGetDocument()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testDeleteDocument().
     */
    public function testDeleteDocument()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
