<?php

	require_once dirname(__FILE__).'/../../../www/libraries/kbi/Integrators/Ontopia.php';

/**
 * Test class for Ontopia.
 * Generated by PHPUnit on 2011-02-14 at 09:38:20.
 */
class OntopiaTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Ontopia
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Ontopia(array(
			'syntax' => 'text/x-tmxml',
			'topicmap' => 'ItalianOpera.ltm',
		));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testGetSyntax()
    {
       $this->assertEquals('text/x-tmxml', $this->object->getSyntax());
    }

    public function testSetSyntax()
    {
		$this->object->setSyntax('test/syntax');
		$this->assertEquals('test/syntax', $this->object->getSyntax());
    }

    public function testGetTopicMap()
    {
		$this->assertEquals('ItalianOpera.ltm', $this->object->getTopicMap());
    }

    public function testSetTopicMap()
    {
        $this->object->setTopicMap('test topic map');
		$this->assertEquals('test topic map', $this->object->getTopicMap());
    }

    /**
     * @todo Implement testQueryGet().
     */
    public function testQueryGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
