<?php

require_once '/Volumes/Data/svn/sewebar/trunk/joomla/www/plugins/kbi/KBIntegrator.php';

/**
 * Test class for KBIntegrator.
 * Generated by PHPUnit on 2011-02-14 at 09:39:04.
 */
class KBIntegratorTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var KBIntegrator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
		$this->object = KBIntegrator::create(array(
			'type' => 'GENERIC',
			'url' => 'http://...',
			'method' => 'POST',
			'port' => '1234',
		));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
		unset($this->object);
    }

    public function testCreate()
    {
		$this->assertInstanceOf('KBIntegrator', $this->object);
    }

    public function testGetUrl()
    {
        $this->assertEquals('http://...', $this->object->getUrl());
    }

    public function testSetUrl()
    {
        $this->object->setUrl('url');
		$this->assertEquals('url', $this->object->getUrl());
    }

    public function testGetMethod()
    {
       $this->assertEquals('POST', $this->object->getMethod());
    }

    public function testSetMethod()
    {
        $this->object->setMethod('GET');
		$this->assertEquals('GET', $this->object->getMethod());
    }

    public function testGetPort()
    {
		$this->assertEquals('1234', $this->object->getPort());
    }

    public function testSetPort()
    {
		$this->object->setPort('8080');
		$this->assertEquals('8080', $this->object->getPort());
    }

    /**
     * @todo Implement test__contruct().
     */
    public function test__contruct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testQuery().
     */
    public function testQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testRequestGet().
     */
    public function testRequestGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testRequestCurl().
     */
    public function testRequestCurl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testRequestCurlPost().
     */
    public function testRequestCurlPost()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testRequestPost().
     */
    public function testRequestPost()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testParseNameValues().
     */
    public function testParseNameValues()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
